name: "check-for-updates"

on:
  workflow_dispatch:
  schedule:
    - cron: '22 11 * * *'

jobs:
  check_version:
    runs-on: ubuntu-latest
    steps:
      - name: Perform setup steps
        uses: JonasAlfredsson/checkout-qemu-buildx@v2
        with:
          should_login: ${{ github.event_name != 'pull_request' }}
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Run the script which checks for new versions
        run: docker run alpine /bin/sh -c "apk search --no-cache rsync | grep -E '^rsync-\d' | cut -d- -f2-" > .github/rsync_version.txt

      - name: Create commit message
        run: echo "COMMIT_MESSAGE=Update to rsync version $(cat .github/rsync_version.txt)" >> $GITHUB_ENV

      - name: Create an authorization token for the pull request step
        uses: actions/create-github-app-token@v2.1.4
        id: generate-token
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7.0.8
        with:
          token: ${{ steps.generate-token.outputs.token }}
          commit-message: ${{ env.COMMIT_MESSAGE }}
          committer: Jonas Alfredsson <jonas.alfredsson@protonmail.com>
          delete-branch: true
          title: ${{ env.COMMIT_MESSAGE }}
          body: Auto-generated by [create-pull-request](https://github.com/peter-evans/create-pull-request).
